on:
  pull_request:
    branches:
      - main

jobs:
  build-with-nix:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build
